# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DotaGuide' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  # Pods for DotaGuide
    pod 'XLPagerTabStrip'
    pod 'Firebase/Analytics'
    pod 'Firebase/Database'
    pod 'SDWebImage'
    
  target 'DotaGuideTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DotaGuideUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
